insert into country values ('AF', 'Afghanistan',                                  'AFG',   4);
insert into country values ('AL', 'Albania',                                      'ALB',   8);
insert into country values ('DZ', 'Algeria',                                      'DZA',  12);
insert into country values ('AS', 'American Samoa',                               'ASM',  16);
insert into country values ('AD', 'Andorra',                                      'AND',  20);
insert into country values ('AO', 'Angola',                                       'AGO',  24);
insert into country values ('AI', 'Anguilla',                                     'AIA', 660);
insert into country values ('AQ', 'Antarctica',                                    null,null);
insert into country values ('AG', 'Antigua and Barbuda',                          'ATG',  28);
insert into country values ('AR', 'Argentina',                                    'ARG',  32);
insert into country values ('AM', 'Armenia',                                      'ARM',  51);
insert into country values ('AW', 'Aruba',                                        'ABW', 533);
insert into country values ('AU', 'Australia',                                    'AUS',  36);
insert into country values ('AT', 'Austria',                                      'AUT',  40);
insert into country values ('AZ', 'Azerbaijan',                                   'AZE',  31);
insert into country values ('BS', 'Bahamas',                                      'BHS',  44);
insert into country values ('BH', 'Bahrain',                                      'BHR',  48);
insert into country values ('BD', 'Bangladesh',                                   'BGD',  50);
insert into country values ('BB', 'Barbados',                                     'BRB',  52);
insert into country values ('BY', 'Belarus',                                      'BLR', 112);
insert into country values ('BE', 'Belgium',                                      'BEL',  56);
insert into country values ('BZ', 'Belize',                                       'BLZ',  84);
insert into country values ('BJ', 'Benin',                                        'BEN', 204);
insert into country values ('BM', 'Bermuda',                                      'BMU',  60);
insert into country values ('BT', 'Bhutan',                                       'BTN',  64);
insert into country values ('BO', 'Bolivia',                                      'BOL',  68);
insert into country values ('BA', 'Bosnia and Herzegovina',                       'BIH',  70);
insert into country values ('BW', 'Botswana',                                     'BWA',  72);
insert into country values ('BV', 'Bouvet Island',                                 null,null);
insert into country values ('BR', 'Brazil',                                       'BRA',  76);
insert into country values ('IO', 'British Indian Ocean Territory',                null,null);
insert into country values ('BN', 'Brunei Darussalam',                            'BRN',  96);
insert into country values ('BG', 'Bulgaria',                                     'BGR', 100);
insert into country values ('BF', 'Burkina Faso',                                 'BFA', 854);
insert into country values ('BI', 'Burundi',                                      'BDI', 108);
insert into country values ('KH', 'Cambodia',                                     'KHM', 116);
insert into country values ('CM', 'Cameroon',                                     'CMR', 120);
insert into country values ('CA', 'Canada',                                       'CAN', 124);
insert into country values ('CV', 'Cape Verde',                                   'CPV', 132);
insert into country values ('KY', 'Cayman Islands',                               'CYM', 136);
insert into country values ('CF', 'Central African Republic',                     'CAF', 140);
insert into country values ('TD', 'Chad',                                         'TCD', 148);
insert into country values ('CL', 'Chile',                                        'CHL', 152);
insert into country values ('CN', 'China',                                        'CHN', 156);
insert into country values ('CX', 'Christmas Island',                              null,null);
insert into country values ('CC', 'Cocos (Keeling) Islands',                       null,null);
insert into country values ('CO', 'Colombia',                                     'COL', 170);
insert into country values ('KM', 'Comoros',                                      'COM', 174);
insert into country values ('CG', 'Congo',                                        'COG', 178);
insert into country values ('CD', 'Congo, the Democratic Republic of the',        'COD', 180);
insert into country values ('CK', 'Cook Islands',                                 'COK', 184);
insert into country values ('CR', 'Costa Rica',                                   'CRI', 188);
insert into country values ('HR', 'Croatia',                                      'HRV', 191);
insert into country values ('CU', 'Cuba',                                         'CUB', 192);
insert into country values ('CY', 'Cyprus',                                       'CYP', 196);
insert into country values ('CZ', 'Czech Republic',                               'CZE', 203);
insert into country values ('DK', 'Denmark',                                      'DNK', 208);
insert into country values ('DJ', 'Djibouti',                                     'DJI', 262);
insert into country values ('DM', 'Dominica',                                     'DMA', 212);
insert into country values ('DO', 'Dominican Republic',                           'DOM', 214);
insert into country values ('EC', 'Ecuador',                                      'ECU', 218);
insert into country values ('EG', 'Egypt',                                        'EGY', 818);
insert into country values ('SV', 'El Salvador',                                  'SLV', 222);
insert into country values ('GQ', 'Equatorial Guinea',                            'GNQ', 226);
insert into country values ('ER', 'Eritrea',                                      'ERI', 232);
insert into country values ('EE', 'Estonia',                                      'EST', 233);
insert into country values ('ET', 'Ethiopia',                                     'ETH', 231);
insert into country values ('FK', 'Falkland Islands (Malvinas)',                  'FLK', 238);
insert into country values ('FO', 'Faroe Islands',                                'FRO', 234);
insert into country values ('FJ', 'Fiji',                                         'FJI', 242);
insert into country values ('FI', 'Finland',                                      'FIN', 246);
insert into country values ('FR', 'France',                                       'FRA', 250);
insert into country values ('GF', 'French Guiana',                                'GUF', 254);
insert into country values ('PF', 'French Polynesia',                             'PYF', 258);
insert into country values ('TF', 'French Southern Territories',                   null,null);
insert into country values ('GA', 'Gabon',                                        'GAB', 266);
insert into country values ('GM', 'Gambia',                                       'GMB', 270);
insert into country values ('GE', 'Georgia',                                      'GEO', 268);
insert into country values ('DE', 'Germany',                                      'DEU', 276);
insert into country values ('GH', 'Ghana',                                        'GHA', 288);
insert into country values ('GI', 'Gibraltar',                                    'GIB', 292);
insert into country values ('GR', 'Greece',                                       'GRC', 300);
insert into country values ('GL', 'Greenland',                                    'GRL', 304);
insert into country values ('GD', 'Grenada',                                      'GRD', 308);
insert into country values ('GP', 'Guadeloupe',                                   'GLP', 312);
insert into country values ('GU', 'Guam',                                         'GUM', 316);
insert into country values ('GT', 'Guatemala',                                    'GTM', 320);
insert into country values ('GN', 'Guinea',                                       'GIN', 324);
insert into country values ('GW', 'Guinea-Bissau',                                'GNB', 624);
insert into country values ('GY', 'Guyana',                                       'GUY', 328);
insert into country values ('HT', 'Haiti',                                        'HTI', 332);
insert into country values ('HM', 'Heard Island and Mcdonald Islands',             null,null);
insert into country values ('VA', 'Holy See (Vatican City State)',                'VAT', 336);
insert into country values ('HN', 'Honduras',                                     'HND', 340);
insert into country values ('HK', 'Hong Kong',                                    'HKG', 344);
insert into country values ('HU', 'Hungary',                                      'HUN', 348);
insert into country values ('IS', 'Iceland',                                      'ISL', 352);
insert into country values ('IN', 'India',                                        'IND', 356);
insert into country values ('ID', 'Indonesia',                                    'IDN', 360);
insert into country values ('IR', 'Iran, Islamic Republic of',                    'IRN', 364);
insert into country values ('IQ', 'Iraq',                                         'IRQ', 368);
insert into country values ('IE', 'Ireland',                                      'IRL', 372);
insert into country values ('IL', 'Israel',                                       'ISR', 376);
insert into country values ('IT', 'Italy',                                        'ITA', 380);
insert into country values ('JM', 'Jamaica',                                      'JAM', 388);
insert into country values ('JP', 'Japan',                                        'JPN', 392);
insert into country values ('JO', 'Jordan',                                       'JOR', 400);
insert into country values ('KZ', 'Kazakhstan',                                   'KAZ', 398);
insert into country values ('KE', 'Kenya',                                        'KEN', 404);
insert into country values ('KI', 'Kiribati',                                     'KIR', 296);
insert into country values ('KR', 'Korea, Republic of',                           'KOR', 410);
insert into country values ('KW', 'Kuwait',                                       'KWT', 414);
insert into country values ('KG', 'Kyrgyzstan',                                   'KGZ', 417);
insert into country values ('LV', 'Latvia',                                       'LVA', 428);
insert into country values ('LB', 'Lebanon',                                      'LBN', 422);
insert into country values ('LS', 'Lesotho',                                      'LSO', 426);
insert into country values ('LR', 'Liberia',                                      'LBR', 430);
insert into country values ('LY', 'Libyan Arab Jamahiriya',                       'LBY', 434);
insert into country values ('LI', 'Liechtenstein',                                'LIE', 438);
insert into country values ('LT', 'Lithuania',                                    'LTU', 440);
insert into country values ('LU', 'Luxembourg',                                   'LUX', 442);
insert into country values ('MO', 'Macao',                                        'MAC', 446);
insert into country values ('MK', 'Macedonia, the Former Yugoslav Republic of',   'MKD', 807);
insert into country values ('MG', 'Madagascar',                                   'MDG', 450);
insert into country values ('MW', 'Malawi',                                       'MWI', 454);
insert into country values ('MY', 'Malaysia',                                     'MYS', 458);
insert into country values ('MV', 'Maldives',                                     'MDV', 462);
insert into country values ('ML', 'Mali',                                         'MLI', 466);
insert into country values ('MT', 'Malta',                                        'MLT', 470);
insert into country values ('MH', 'Marshall Islands',                             'MHL', 584);
insert into country values ('MQ', 'Martinique',                                   'MTQ', 474);
insert into country values ('MR', 'Mauritania',                                   'MRT', 478);
insert into country values ('MU', 'Mauritius',                                    'MUS', 480);
insert into country values ('YT', 'Mayotte',                                       null,null);
insert into country values ('MX', 'Mexico',                                       'MEX', 484);
insert into country values ('FM', 'Micronesia, Federated States of',              'FSM', 583);
insert into country values ('MD', 'Moldova, Republic of',                         'MDA', 498);
insert into country values ('MC', 'Monaco',                                       'MCO', 492);
insert into country values ('MN', 'Mongolia',                                     'MNG', 496);
insert into country values ('MS', 'Montserrat',                                   'MSR', 500);
insert into country values ('MA', 'Morocco',                                      'MAR', 504);
insert into country values ('MZ', 'Mozambique',                                   'MOZ', 508);
insert into country values ('MM', 'Myanmar',                                      'MMR', 104);
insert into country values ('NA', 'Namibia',                                      'NAM', 516);
insert into country values ('NR', 'Nauru',                                        'NRU', 520);
insert into country values ('NP', 'Nepal',                                        'NPL', 524);
insert into country values ('NL', 'Netherlands',                                  'NLD', 528);
insert into country values ('AN', 'Netherlands Antilles',                         'ANT', 530);
insert into country values ('NC', 'New Caledonia',                                'NCL', 540);
insert into country values ('NZ', 'New Zealand',                                  'NZL', 554);
insert into country values ('NI', 'Nicaragua',                                    'NIC', 558);
insert into country values ('NE', 'Niger',                                        'NER', 562);
insert into country values ('NG', 'Nigeria',                                      'NGA', 566);
insert into country values ('NU', 'Niue',                                         'NIU', 570);
insert into country values ('NF', 'Norfolk Island',                               'NFK', 574);
insert into country values ('MP', 'Northern Mariana Islands',                     'MNP', 580);
insert into country values ('NO', 'Norway',                                       'NOR', 578);
insert into country values ('OM', 'Oman',                                         'OMN', 512);
insert into country values ('PK', 'Pakistan',                                     'PAK', 586);
insert into country values ('PW', 'Palau',                                        'PLW', 585);
insert into country values ('PS', 'Palestinian Territory',                         null,null);
insert into country values ('PA', 'Panama',                                       'PAN', 591);
insert into country values ('PG', 'Papua New Guinea',                             'PNG', 598);
insert into country values ('PY', 'Paraguay',                                     'PRY', 600);
insert into country values ('PE', 'Peru',                                         'PER', 604);
insert into country values ('PH', 'Philippines',                                  'PHL', 608);
insert into country values ('PN', 'Pitcairn',                                     'PCN', 612);
insert into country values ('PL', 'Poland',                                       'POL', 616);
insert into country values ('PT', 'Portugal',                                     'PRT', 620);
insert into country values ('PR', 'Puerto Rico',                                  'PRI', 630);
insert into country values ('QA', 'Qatar',                                        'QAT', 634);
insert into country values ('RE', 'Reunion',                                      'REU', 638);
insert into country values ('RO', 'Romania',                                      'ROM', 642);
insert into country values ('RU', 'Russian Federation',                           'RUS', 643);
insert into country values ('RW', 'Rwanda',                                       'RWA', 646);
insert into country values ('SH', 'Saint Helena',                                 'SHN', 654);
insert into country values ('KN', 'Saint Kitts and Nevis',                        'KNA', 659);
insert into country values ('LC', 'Saint Lucia',                                  'LCA', 662);
insert into country values ('PM', 'Saint Pierre and Miquelon',                    'SPM', 666);
insert into country values ('VC', 'Saint Vincent and the Grenadines',             'VCT', 670);
insert into country values ('WS', 'Samoa',                                        'WSM', 882);
insert into country values ('SM', 'San Marino',                                   'SMR', 674);
insert into country values ('ST', 'Sao Tome and Principe',                        'STP', 678);
insert into country values ('SA', 'Saudi Arabia',                                 'SAU', 682);
insert into country values ('SN', 'Senegal',                                      'SEN', 686);
insert into country values ('CS', 'Serbia and Montenegro',                         null,null);
insert into country values ('SC', 'Seychelles',                                   'SYC', 690);
insert into country values ('SL', 'Sierra Leone',                                 'SLE', 694);
insert into country values ('SG', 'Singapore',                                    'SGP', 702);
insert into country values ('SK', 'Slovakia',                                     'SVK', 703);
insert into country values ('SI', 'Slovenia',                                     'SVN', 705);
insert into country values ('SB', 'Solomon Islands',                              'SLB',  90);
insert into country values ('SO', 'Somalia',                                      'SOM', 706);
insert into country values ('ZA', 'South Africa',                                 'ZAF', 710);
insert into country values ('GS', 'South Georgia and the South Sandwich Islands',  null,null);
insert into country values ('ES', 'Spain',                                        'ESP', 724);
insert into country values ('LK', 'Sri Lanka',                                    'LKA', 144);
insert into country values ('SD', 'Sudan',                                        'SDN', 736);
insert into country values ('SR', 'Suriname',                                     'SUR', 740);
insert into country values ('SJ', 'Svalbard and Jan Mayen',                       'SJM', 744);
insert into country values ('SZ', 'Swaziland',                                    'SWZ', 748);
insert into country values ('SE', 'Sweden',                                       'SWE', 752);
insert into country values ('CH', 'Switzerland',                                  'CHE', 756);
insert into country values ('SY', 'Syrian Arab Republic',                         'SYR', 760);
insert into country values ('TW', 'Taiwan, Province of China',                    'TWN', 158);
insert into country values ('TJ', 'Tajikistan',                                   'TJK', 762);
insert into country values ('TZ', 'Tanzania, United Republic of',                 'TZA', 834);
insert into country values ('TH', 'Thailand',                                     'THA', 764);
insert into country values ('TL', 'Timor-Leste',                                   null,null);
insert into country values ('TG', 'Togo',                                         'TGO', 768);
insert into country values ('TK', 'Tokelau',                                      'TKL', 772);
insert into country values ('TO', 'Tonga',                                        'TON', 776);
insert into country values ('TT', 'Trinidad and Tobago',                          'TTO', 780);
insert into country values ('TN', 'Tunisia',                                      'TUN', 788);
insert into country values ('TR', 'Turkey',                                       'TUR', 792);
insert into country values ('TM', 'Turkmenistan',                                 'TKM', 795);
insert into country values ('TC', 'Turks and Caicos Islands',                     'TCA', 796);
insert into country values ('TV', 'Tuvalu',                                       'TUV', 798);
insert into country values ('UG', 'Uganda',                                       'UGA', 800);
insert into country values ('UA', 'Ukraine',                                      'UKR', 804);
insert into country values ('AE', 'United Arab Emirates',                         'ARE', 784);
insert into country values ('GB', 'United Kingdom',                               'GBR', 826);
insert into country values ('US', 'United States',                                'USA', 840);
insert into country values ('UM', 'United States Minor Outlying Islands',          null,null);
insert into country values ('UY', 'Uruguay',                                      'URY', 858);
insert into country values ('UZ', 'Uzbekistan',                                   'UZB', 860);
insert into country values ('VU', 'Vanuatu',                                      'VUT', 548);
insert into country values ('VE', 'Venezuela',                                    'VEN', 862);
insert into country values ('VN', 'Viet Nam',                                     'VNM', 704);
insert into country values ('VG', 'Virgin Islands, British',                      'VGB',  92);
insert into country values ('VI', 'Virgin Islands, U.s.',                         'VIR', 850);
insert into country values ('WF', 'Wallis and Futuna',                            'WLF', 876);
insert into country values ('EH', 'Western Sahara',                               'ESH', 732);
insert into country values ('YE', 'Yemen',                                        'YEM', 887);
insert into country values ('ZM', 'Zambia',                                       'ZMB', 894);
insert into country values ('ZW', 'Zimbabwe',                                     'ZWE', 716);
insert into country values ('CI', 'Cote D''Ivoire',                               'CIV', 384);
insert into country values ('KP', 'Korea, Democratic People''s Republic of',      'PRK', 408);
insert into country values ('LA', 'Lao People''s Democratic Republic',            'LAO', 418);
