insert into currency values ('AED', 'United Arab Emirates Dirham'         ); 
insert into currency values ('AFN', 'Afghan Afghani'                      ); 
insert into currency values ('ALL', 'Albanian Lek'                        ); 
insert into currency values ('AMD', 'Armenian Dram'                       ); 
insert into currency values ('ANG', 'Netherlands Antillean Guilder'       ); 
insert into currency values ('AOA', 'Angolan Kwanza'                      ); 
insert into currency values ('ARS', 'Argentine Peso'                      ); 
insert into currency values ('AUD', 'Australian Dollar'                   ); 
insert into currency values ('AWG', 'Aruban Florin'                       ); 
insert into currency values ('AZN', 'Azerbaijani Manat'                   ); 
insert into currency values ('BAM', 'Bosnia-Herzegovina Convertible Mark' ); 
insert into currency values ('BBD', 'Barbadian Dollar'                    ); 
insert into currency values ('BDT', 'Bangladeshi Taka'                    ); 
insert into currency values ('BGN', 'Bulgarian Lev'                       ); 
insert into currency values ('BHD', 'Bahraini Dinar'                      ); 
insert into currency values ('BIF', 'Burundian Franc'                     ); 
insert into currency values ('BMD', 'Bermudan Dollar'                     ); 
insert into currency values ('BND', 'Brunei Dollar'                       ); 
insert into currency values ('BOB', 'Bolivian Boliviano'                  ); 
insert into currency values ('BRL', 'Brazilian Real'                      ); 
insert into currency values ('BSD', 'Bahamian Dollar'                     ); 
insert into currency values ('BTN', 'Bhutanese Ngultrum'                  ); 
insert into currency values ('BWP', 'Botswanan Pula'                      ); 
insert into currency values ('BYR', 'Belarusian Ruble'                    ); 
insert into currency values ('BZD', 'Belize Dollar'                       ); 
insert into currency values ('CAD', 'Canadian Dollar'                     ); 
insert into currency values ('CDF', 'Congolese Franc'                     ); 
insert into currency values ('CHF', 'Swiss Franc'                         ); 
insert into currency values ('CLF', 'Chilean Unit of Account (UF)'        ); 
insert into currency values ('CLP', 'Chilean Peso'                        ); 
insert into currency values ('CNY', 'Chinese Yuan'                        ); 
insert into currency values ('COP', 'Colombian Peso'                      ); 
insert into currency values ('CRC', 'Costa Rican Colón'                   ); 
insert into currency values ('CUP', 'Cuban Peso'                          ); 
insert into currency values ('CVE', 'Cape Verdean Escudo'                 ); 
insert into currency values ('CZK', 'Czech Republic Koruna'               ); 
insert into currency values ('DJF', 'Djiboutian Franc'                    ); 
insert into currency values ('DKK', 'Danish Krone'                        ); 
insert into currency values ('DOP', 'Dominican Peso'                      ); 
insert into currency values ('DZD', 'Algerian Dinar'                      ); 
insert into currency values ('EEK', 'Estonian Kroon'                 )/*?*/;
insert into currency values ('EGP', 'Egyptian Pound'                      ); 
insert into currency values ('ETB', 'Ethiopian Birr'                      ); 
insert into currency values ('EUR', 'Euro'                                ); 
insert into currency values ('FJD', 'Fijian Dollar'                       ); 
insert into currency values ('FKP', 'Falkland Islands Pound'              ); 
insert into currency values ('GBP', 'British Pound Sterling'              ); 
insert into currency values ('GEL', 'Georgian Lari'                       ); 
insert into currency values ('GHS', 'Ghanaian Cedi'                       ); 
insert into currency values ('GIP', 'Gibraltar Pound'                     ); 
insert into currency values ('GMD', 'Gambian Dalasi'                      ); 
insert into currency values ('GNF', 'Guinean Franc'                       ); 
insert into currency values ('GTQ', 'Guatemalan Quetzal'                  ); 
insert into currency values ('GYD', 'Guyanaese Dollar'                    ); 
insert into currency values ('HKD', 'Hong Kong Dollar'                    ); 
insert into currency values ('HNL', 'Honduran Lempira'                    ); 
insert into currency values ('HRK', 'Croatian Kuna'                       ); 
insert into currency values ('HTG', 'Haitian Gourde'                      ); 
insert into currency values ('HUF', 'Hungarian Forint'                    ); 
insert into currency values ('IDR', 'Indonesian Rupiah'                   ); 
insert into currency values ('IEP', 'Irish Pound'                         ); 
insert into currency values ('ILS', 'Israeli New Sheqel'                  ); 
insert into currency values ('INR', 'Indian Rupee'                        ); 
insert into currency values ('IQD', 'Iraqi Dinar'                         ); 
insert into currency values ('IRR', 'Iranian Rial'                        ); 
insert into currency values ('ISK', 'Icelandic Króna'                     ); 
insert into currency values ('JMD', 'Jamaican Dollar'                     ); 
insert into currency values ('JOD', 'Jordanian Dinar'                     ); 
insert into currency values ('JPY', 'Japanese Yen'                        ); 
insert into currency values ('KES', 'Kenyan Shilling'                     ); 
insert into currency values ('KGS', 'Kyrgystani Som'                      ); 
insert into currency values ('KHR', 'Cambodian Riel'                      ); 
insert into currency values ('KMF', 'Comorian Franc'                      ); 
insert into currency values ('KPW', 'North Korean Won'                    ); 
insert into currency values ('KRW', 'South Korean Won'                    ); 
insert into currency values ('KWD', 'Kuwaiti Dinar'                       ); 
insert into currency values ('KYD', 'Cayman Islands Dollar'          )/*?*/;
insert into currency values ('KZT', 'Kazakhstani Tenge'                   ); 
insert into currency values ('LAK', 'Laotian Kip'                         ); 
insert into currency values ('LBP', 'Lebanese Pound'                      ); 
insert into currency values ('LKR', 'Sri Lankan Rupee'                    ); 
insert into currency values ('LRD', 'Liberian Dollar'                     ); 
insert into currency values ('LSL', 'Lesotho Loti'                        ); 
insert into currency values ('LTL', 'Lithuanian Litas'                    ); 
insert into currency values ('LVL', 'Latvian Lats'                        ); 
insert into currency values ('LYD', 'Libyan Dinar'                        ); 
insert into currency values ('MAD', 'Moroccan Dirham'                     ); 
insert into currency values ('MDL', 'Moldovan Leu'                        ); 
insert into currency values ('MGA', 'Malagasy Ariary'                     ); 
insert into currency values ('MKD', 'Macedonian Denar'                    ); 
insert into currency values ('MMK', 'Myanma Kyat'                         ); 
insert into currency values ('MNT', 'Mongolian Tugrik'                    ); 
insert into currency values ('MOP', 'Macanese Pataca'                     ); 
insert into currency values ('MRO', 'Mauritanian Ouguiya'                 ); 
insert into currency values ('MUR', 'Mauritian Rupee'                     ); 
insert into currency values ('MVR', 'Maldivian Rufiyaa'                   ); 
insert into currency values ('MWK', 'Malawian Kwacha'                     ); 
insert into currency values ('MXN', 'Mexican Peso'                        ); 
insert into currency values ('MYR', 'Malaysian Ringgit'                   ); 
insert into currency values ('MZN', 'Mozambican Metical'                  ); 
insert into currency values ('NAD', 'Namibian Dollar'                     ); 
insert into currency values ('NGN', 'Nigerian Naira'                      ); 
insert into currency values ('NIO', 'Nicaraguan Córdoba'                  ); 
insert into currency values ('NOK', 'Norwegian Krone'                     ); 
insert into currency values ('NPR', 'Nepalese Rupee'                      ); 
insert into currency values ('NZD', 'New Zealand Dollar'                  ); 
insert into currency values ('OMR', 'Omani Rial'                          ); 
insert into currency values ('PAB', 'Panamanian Balboa'                   ); 
insert into currency values ('PEN', 'Peruvian Nuevo Sol'                  ); 
insert into currency values ('PGK', 'Papua New Guinean Kina'              ); 
insert into currency values ('PHP', 'Philippine Peso'                     ); 
insert into currency values ('PKR', 'Pakistani Rupee'                     ); 
insert into currency values ('PLN', 'Polish Zloty'                        ); 
insert into currency values ('PYG', 'Paraguayan Guarani'                  ); 
insert into currency values ('QAR', 'Qatari Rial'                         ); 
insert into currency values ('RON', 'Romanian Leu'                        ); 
insert into currency values ('RSD', 'Serbian Dinar'                       ); 
insert into currency values ('RUB', 'Russian Ruble'                       ); 
insert into currency values ('RWF', 'Rwandan Franc'                       ); 
insert into currency values ('SAR', 'Saudi Riyal'                         ); 
insert into currency values ('SBD', 'Solomon Islands Dollar'              ); 
insert into currency values ('SCR', 'Seychellois Rupee'                   ); 
insert into currency values ('SDG', 'Sudanese Pound'                      ); 
insert into currency values ('SEK', 'Swedish Krona'                       ); 
insert into currency values ('SGD', 'Singapore Dollar'                    ); 
insert into currency values ('SKK', 'Slovak Koruna'                  )/*?*/;
insert into currency values ('SHP', 'Saint Helena Pound'                  ); 
insert into currency values ('SLL', 'Sierra Leonean Leone'                ); 
insert into currency values ('SOS', 'Somali Shilling'                     ); 
insert into currency values ('SRD', 'Surinamese Dollar'                   ); 
insert into currency values ('STD', 'São Tomé and Príncipe Dobra'         ); 
insert into currency values ('SVC', 'Salvadoran Colón'                    ); 
insert into currency values ('SYP', 'Syrian Pound'                        ); 
insert into currency values ('SZL', 'Swazi Lilangeni'                     ); 
insert into currency values ('THB', 'Thai Baht'                           ); 
insert into currency values ('TJS', 'Tajikistani Somoni'                  ); 
insert into currency values ('TMT', 'Turkmenistani Manat'                 ); 
insert into currency values ('TND', 'Tunisian Dinar'                      ); 
insert into currency values ('TOP', 'Tongan Paʻanga'                      ); 
insert into currency values ('TRY', 'Turkish Lira'                        ); 
insert into currency values ('TTD', 'Trinidad and Tobago Dollar'          ); 
insert into currency values ('TWD', 'New Taiwan Dollar'                   ); 
insert into currency values ('TZS', 'Tanzanian Shilling'                  ); 
insert into currency values ('UAH', 'Ukrainian Hryvnia'                   ); 
insert into currency values ('UGX', 'Ugandan Shilling'                    ); 
insert into currency values ('USD', 'United States Dollar'                ); 
insert into currency values ('UYU', 'Uruguayan Peso'                      ); 
insert into currency values ('UZS', 'Uzbekistan Som'                      ); 
insert into currency values ('VEF', 'Venezuelan Bolívar'                  ); 
insert into currency values ('VND', 'Vietnamese Dong'                     ); 
insert into currency values ('VUV', 'Vanuatu Vatu'                        ); 
insert into currency values ('WST', 'Samoan Tala'                         ); 
insert into currency values ('XAF', 'CFA Franc BEAC'                      ); 
insert into currency values ('XCD', 'East Caribbean Dollar'               ); 
insert into currency values ('XDR', 'Special Drawing Rights'              ); 
insert into currency values ('XOF', 'CFA Franc BCEAO'                     ); 
insert into currency values ('XPF', 'CFP Franc'                           ); 
insert into currency values ('YER', 'Yemeni Rial'                         ); 
insert into currency values ('ZAR', 'South African Rand'                  ); 
insert into currency values ('ZMK', 'Zambian Kwacha'                      ); 
insert into currency values ('ZWD', 'Zimbabwean Dollar (1980-2008)'       ); 
insert into currency values ('ZWL', 'Zimbabwean Dollar'                   ); 
